name: Python package

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7","3.8","3.9","3.10"]
        
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install clir using Poetry
        run: |
          poetry install ; poetry build ; pip install .
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov coverage
          pytest -v -s tests/init_clir.py tests/add_command.py tests/remove_command.py
