name: Test Clir

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8","3.9","3.10"]
        
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install xclip
        if: runner.os == 'ubuntu-latest'  # Run only if the OS is Linux (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y xclip
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install clir using Poetry
        run: |
          poetry install ; poetry build ; pip install .
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov coverage pyperclip
          pytest -v -s tests/1-init_clir.py tests/2-add_command.py tests/3-copy_command.py tests/4-run_command.py tests/5-remove_command.py tests/6-list_command.py
